upstream backend_pool {
    least_conn;
    server backend1:3000 max_fails=3 fail_timeout=10s;
    server backend2:3000 max_fails=3 fail_timeout=10s;
    server backend3:3000 max_fails=3 fail_timeout=10s;

    # this uses the connection pool to keep connections to the backend open for reuse
    keepalive 64;
}

# ACTIVE HEALTH CHECK

init_worker_by_lua_block {
    local hc = require "resty.upstream.healthcheck"

    local ok, err = hc.spawn_checker{
        shm = "healthcheck",
        upstream = "backend_pool",
        type = "http",
        http_req = "GET /health HTTP/1.0\r\nHost: localhost\r\n\r\n",
        interval = 2000,      -- probe every 2 seconds
        timeout = 1000,       -- 1 second timeout per probe
        fall = 3,             -- 3 consecutive failures marks a backend down
        rise = 2,             -- 2 consecutive successes marks it back up
        valid_statuses = {200},
        concurrency = 5,
    }

    if not ok then
        ngx.log(ngx.ERR, "failed to spawn health checker: ", err)
    end
}

server {
    listen 80;    # default http port

    # used by the nginx-prometheus-exporter container, keep this locked down to internal traffic only in anything beyond a local learning project
    location /stub_status {
        stub_status;
        allow all;
    }

    # human-readable view of what the active health checker currently thinks is up or down when the user enters : localhost:8080/healthcheck_status in their browser
    location = /healthcheck_status {
        access_log off;
        content_by_lua_block {
            local hc = require "resty.upstream.healthcheck"
            ngx.say("Nginx Worker PID: ", ngx.worker.pid())
            ngx.print(hc.status_page())
        }
    }

    # more specific location, matched before /api/ for requests to /api/hot
    location /api/hot {
        proxy_cache hot_cache;
        proxy_cache_valid 200 30s;
        add_header X-Cache-Status $upstream_cache_status;

        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_pass http://backend_pool/hot;
    }

    location /api/ {
        limit_req zone=api_limit burst=20 nodelay;

        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_pass http://backend_pool/;
    }
}
